# Generated by Django 6.0 on 2026-01-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_category_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Service Charge %'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='VAT %'),
        ),
    ]
