# Generated by Django 6.0 on 2026-01-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payment_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qrs/', verbose_name='QR Code รับเงิน (ธนาคาร)'),
        ),
    ]
