# Generated by Django 6.0 on 2026-01-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_payment_qr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPromoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promo_images/', verbose_name='รูปโปรโมชั่น/เมนูแนะนำ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_images', to='restaurants.restaurant')),
            ],
        ),
    ]
